[package]
name = "rt-thread_rs"
version = "0.1.0"
authors = ["thread-liu <lk9608@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
